name: 'Website Screenshot Capture'
description: 'Action to capture screenshots of web pages.'
branding:
  icon: image
  color: green

inputs:
  url:
    description: 'URL of the webpage to capture.'
    required: false

  name:
    description: 'File name for the screenshot.'
    required: false

  urls_input_file:
    description: 'File containing a list of pages to process. If provided, "url" will be ignored.'
    required: false

  width:
    description: 'Width of the screenshot in pixels (default: 1366).'
    default: '1366'
    required: false

  height:
    description: 'Height of the screenshot in pixels (default: 768).'
    default: '768'
    required: false

  type:
    description: 'Image format for the screenshot (default: png). Options: webp, jpeg, png.'
    default: 'png'
    required: false

  quality:
    description: 'Quality of the image (only applicable for jpeg and webp). Range: 0 to 100 (default: 100).'
    default: '100'
    required: false

  output_dir:
    description: 'Output dir'
    default: 'screenshots'
    required: false

outputs:
  screenshot-path:
    description: 'Path where the screenshot is saved'

runs:
  using: node20
  main: dist/index.js
